### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by wojciechAdaszynski** [psmarcin/react-redux-best-practices#2]
From what I understand there are *two* factors to consider while choosing immutability lib for our project. 
1. **Performance** - only immutable.js implements fully featured persistent data structures. While it may not slow down simple components, it could decrease performance of tables
2.  **Developer experience** - *immutable.js*, *react addons* and *tcomb* provide very complicated and unintuitive mechanism for manipulating fields while *seamless-immutable* tries to be similar to vanilla js 

------------
Resources:
https://www.reddit.com/r/javascript/comments/44ungq/switching_from_immutablejs_to_seamlessimmutable/ (especially @Cody_Chaos comment)
https://news.ycombinator.com/item?id=10060029
https://github.com/rtfeldman/seamless-immutable
https://en.wikipedia.org/wiki/Persistent_data_structure

**Comment by psmarcin** [comment]
I vote for immutable, because for example:
```javascript
var array = Immutable(["totally", "immutable", {hammer: "Can’t Touch This"}]);
array[1] = "I'm going to mutate you!"
array[1] // "immutable"

array[2].hammer = "hm, surely I can mutate this nested object..."
array[2].hammer // "Can’t Touch This"
```
You are able to 'update' but it doesnt update, so I think it may cause many problems for developers. 
I would like to listen other devs opinions

**Comment by psmarcin** [comment]
Ok nobody want to talk more about this so I decided to use `Immutable.js`.
