### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by wojciechAdaszynski** [psmarcin/react-redux-best-practices#3]
Sass-loader is great for apps with many components, but it does not solve name collision problem. What do you think about applying BEM methodology in larger projects?

http://getbem.com/introduction/

**Comment by psmarcin** [comment]
Thats good idea, Igor mentions that last time I was talking about that.

**Comment by igorko82** [comment]
I think BEM will be good idea for this project. We can use simple function for generation of classnames like this https://github.com/sunify/bem-classname or we can write own.

So our sass will look like this:
`
$module: 'note';

.#{$module} {
  &__content {
    background: white;
  }

  &--featured {
    .#{$module}__content {
      background: #eee;
    }
  }
}
`

End component like this:

`
import React from 'react';
import bemClassName from 'bem-classname';

class SomeComp {

  static propTypes = {
    items: React.PropTypes.array
  };

  constructor() {
    this.className = bemClassName.bind(null, this.constructor.name);
  }

  /**
   * className() === 'SomeComp'
   * className('title') === 'SomeComp__title'
   * className('item', {awesome: true}) === 'SomeComp__item SomeComp__item--awesome'
   * className('item', {awesome: false}) === 'SomeComp__item'
   */
  render() {
    const { className } = this;
    return (
      <div className={className()}>
        <h2 className={className('title')}>Title</h2>
        <ul className={className('list')}>
          {this.props.items.map((item) => (
            <li className={className('item', {awesome: item.isAwesome})}>
              {item.text}
            </li>
          ))}
        </ul>
      </div>
    );
  }

}
`

**Comment by psmarcin** [comment]
@igorko82 it looks amazing. I really like this, we definetely should implement that. Can you create PR for this?

**Comment by igorko82** [comment]
Yes, i'll do it

**Comment by psmarcin** [comment]
Thanks, so I will colse that issue as resolved
